apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: teste.exemple.com
    - http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: nginx-svc
                port:
                  name: metrics
